declare module '*.png';
declare module '*.jpg';
declare module '*.gif';
declare module '*.less';
declare module '*.svg';
declare module '*.ico';
declare module '*.js';
declare module '*.json';
declare module '*.mdx';
